apiVersion: policy.sigstore.dev/v1alpha1
kind: ClusterImagePolicy
metadata:
  name: sample-docker-monorepo
spec:
  images:
  - glob: "ghcr.io/bobymcbobs/sample-docker-monorepo**"
  authorities:
  - keyless:
      identities:
      - issuer: https://token.actions.githubusercontent.com
        subjectRegExp: "^(https://github.com/BobyMCbobs/sample-docker-monorepo/.github/workflows/reusable-build.yml@refs/(heads/main|tags/v[0-9].[0-9].[0-9]))$"
