name: dockerfile-lint
on:
  push: {}
  pull_request: {}
  workflow_dispatch: {}
jobs:
  dockerfile-lint:
    uses: BobyMCbobs/sample-docker-monorepo/.github/workflows/reusable-dockerfile-lint.yml@main
