name: golangci lint
on:
  workflow_dispatch: {}
  push:
    branches:
      - main
      - master
      - canon
  pull_request: {}
permissions:
  contents: read
  pull-requests: read
jobs:
  golangci:
    uses: BobyMCbobs/sample-docker-monorepo/.github/workflows/reusable-golangci-lint.yml@main
