name: Presubmit Actions workflow vet

on:
  pull_request:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  presubmit-workflow:
    uses: BobyMCbobs/sample-docker-monorepo/.github/workflows/reusable-presubmit-actions-workflow-require-commit-digest-vet.yml@main
