name: reusable update actions imports versions

on:
  workflow_call: {}

jobs:
  presubmit-workflow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f095bcc56b7c2baf48f3ac70d6d6782f4f553222
      - uses: mikefarah/yq@bbe305500687a5fe8498d74883c17f0f06431ac4
      - id: actions-per-workflow
        run: |
          # steps
          # 1. get jobs from uses fields
          ACTIONS=$(
            for WORKFLOW in $(find .github/workflows -type f -name '*.yml'); do
              ACTIONS=$(< $WORKFLOW \
                yq e '.jobs.*.steps[].uses as $jobsteps | .jobs.*.uses as $jobuses | $jobsteps | [., $jobuses]' -o json \
                  | jq -rcMs --arg file "$WORKFLOW" --arg repository "$REPOSITORY" '{"actions": . | flatten} | .file = $file')
              [ -z "${ACTIONS}" ] && continue
              echo -e "${ACTIONS}"
            done | jq -sc '.'
          )
          echo "actions=$ACTIONS" >> $GITHUB_OUTPUT
      - name: display actions
        run: |
          echo -e '${{ steps.actions-per-workflow.outputs.actions }}' | yq e -P
      - name: iterate through each file's actions and update them
        run: |
          ACTIONS="$(echo ${{ steps.actions-per-workflow.outputs.actions }} | jq -rcM .[])"
          while IFS= read -r ACTION_FILE; do
            echo "${ACTION_FILE}" | jq .
          done << "$ACTIONS"
      # 1. get latest release
      #   1a. get tag of release, returning commit hash
      # 2. if no latest release,
      #    determine main branch name and
      #    return latest commit on the $MAIN branch
